services:
  gphotos-takeout:
    container_name: gphotos-takeout
    hostname: gphotos-takeout
    image: ghcr.io/l480/gphotos-takeout:latest
    user: "1000:1000"
    restart: unless-stopped
    environment:
      RCLONE_DRIVE_REMOTE: gdrive:Takeout
      RCLONE_S3_REMOTE: s3:my-bucket
      RCLONE_TRANSFERS: "1"
      RCLONE_CHECKERS: "2"
      RCLONE_LOG_LEVEL: INFO
    volumes:
      - /opt/gphotos-takeout:/config/rclone
